IF OBJECT_ID ('bronze.novelupdates', 'U') IS NOT NULL
    DROP TABLE bronze.novelupdates;

CREATE TABLE bronze.novelupdates (
    novelupdates_id INT,
    novelupdates_name NVARCHAR(MAX),
    novelupdates_novel_type NVARCHAR(50),
    novelupdates_cover_url NVARCHAR(50),
    novelupdates_assoc_names NVARCHAR(MAX),
    novelupdates_original_language NVARCHAR(50),
    novelupdates_authors NVARCHAR(50),
    novelupdates_genres NVARCHAR(MAX),
    novelupdates_tags NVARCHAR(MAX),
    novelupdates_start_year INT,
    novelupdates_licensed NVARCHAR(50),
    novelupdates_original_publisher NVARCHAR(50),
    novelupdates_english_publisher NVARCHAR(50),
    novelupdates_complete_original NVARCHAR(50),
    novelupdates_chapters_original_current NVARCHAR(50),
    novelupdates_complete_translated NVARCHAR(50),
    novelupdates_release_freq NVARCHAR(50),
    novelupdates_activity_week_rank NVARCHAR(50),
    novelupdates_activity_month_rank NVARCHAR(50),
    novelupdates_activity_all_time_rank NVARCHAR(50),
    novelupdates_on_reading_lists NVARCHAR(50),
    novelupdates_reading_list_month_rank NVARCHAR(50),
    novelupdates_reading_list_all_time_rank NVARCHAR(50),
    novelupdates_rating NVARCHAR(50),
    novelupdates_rating_votes NVARCHAR(50),
    novelupdates_related_series_ids NVARCHAR(50),
    novelupdates_recommended_series_ids NVARCHAR(50),
    novelupdates_recommendation_list_ids NVARCHAR(50),
    novelupdates_chapter_latest_translated NVARCHAR(50)
);

IF OBJECT_ID ('bronze.webnovel', 'U') IS NOT NULL
    DROP TABLE bronze.webnovel;

CREATE TABLE bronze.webnovel (
    webnovel_novel_id INT,
    webnovel_url NVARCHAR(500),
    webnovel_title NVARCHAR(MAX),
    webnovel_associated_names NVARCHAR(MAX),
    webnovel_img_url NVARCHAR(250),
    webnovel_showtype NVARCHAR(250),
    webnovel_genres NVARCHAR(MAX),
    webnovel_tags NVARCHAR(MAX),
    webnovel_description NVARCHAR(MAX),
    webnovel_related_series NVARCHAR(500),
    webnovel_recommendations NVARCHAR(MAX),
    webnovel_recommendation_lists NVARCHAR(MAX),
    webnovel_rating NVARCHAR(250),
    webnovel_language NVARCHAR(50),
    webnovel_authors NVARCHAR(250),
    webnovel_artists NVARCHAR(250),
    webnovel_year NVARCHAR(50),
    webnovel_status_coo NVARCHAR(250),
    webnovel_licensed NVARCHAR(50),
    webnovel_translated NVARCHAR(50),
    webnovel_publishers NVARCHAR(50),
    webnovel_en_pubs NVARCHAR(250),
    webnovel_release_frequency NVARCHAR(50),
    webnovel_weekly_rank NVARCHAR(50),
    webnovel_monthly_rank NVARCHAR(50),
    webnovel_all_time_rank NVARCHAR(50),
    webnovel_monthly_rank_reading_list NVARCHAR(50),
    webnovel_all_time_rank_reading_list NVARCHAR(50),
    webnovel_total_reading_list_rank NVARCHAR(50),
    webnovel_chapters NVARCHAR(MAX)
);
